backend:
  name: git-gateway
  local_backend:
    true
    # when using a custom proxy server port
  url: http://localhost:8082/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['192.168.0.1']
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  # Collection of unique, root level pages that aren't to be built over and over
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing page'
        name: 'index'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page' }
          # hero banner, title and subheading
          - {
              label: 'Landing Box',
              name: landingBox,
              widget: object,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Title, name: title, widget: string },
                  { label: Subheading, name: subheading, widget: string }
                ]
            }
          - { label: 'Catchy Banner', name: catchyBanner, widget: object, fields: [{ label: Body, name: body, widget: markdown }] }
          - {
              label: 'Page Sections',
              name: pageSections,
              widget: object,
              fields:
                [
                  {
                    label: Section,
                    name: section,
                    widget: list,
                    default: [{ image: null, subheading: '', text: '' }],
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Subheading, name: subheading, widget: string },
                        { label: Text, name: text, widget: 'markdown' },
                        { label: ButtonText, name: buttonText, widget: 'string', default: 'Learn more' },
                        {
                          label: ButtonLocation,
                          name: buttonLocation,
                          widget: 'select',
                          options:
                            [
                              '/',
                              '/about',
                              '/leagues/drop-in',
                              '/registrations',
                              '/technical/rules-and-reffing',
                              '/technical/bylaws',
                              '/technical/dbo-tips',
                              '/technical/membership',
                              '/technical/covid-19-protocol',
                              '/events',
                              '/galleries',
                              '/contact'
                            ],
                          default: ['/']
                        }
                      ]
                  }
                ]
            }

      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'About'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  # Collection of all pages found in the technical menu
  - label: 'Technical pages'
    label_singular: 'technical page'
    name: 'technical-pages'
    folder: 'src/pages/technical'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'technical-page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Technical page sections',
          name: 'technicalPageSections',
          widget: 'object',
          fields: [{
            label: Section,
            name: technicalSection,            
            widget: list,
            fields: [
              { label: Subheading, name: subheading, widget: string },
              { label: 'Heading level', name: headingLevel, widget: 'select', options: ['h2', 'h3', 'h4', 'h5', 'h6'], default: 'h2', required: false },
              { label: ID, name: id, widget: string, required: false },
              { label: Image, name: image, widget: image, default: '', required: false },
              { label: Alt text, name: alt, widget: string, required: false },
              { label: 'Image float', name: imageFloat, widget: 'select', options: ['Left', 'Right'], default: 'default', required: false },
              { label: 'Image width', name: imageWidth, widget: 'select', options: ['25%', '50%', '75%'], default: 'default', required: false },
              { label: Text, name: text, widget: 'markdown', default: "", required: false },
              { label: 'Second column text', name: extraText, widget: 'markdown', default: "", required: false }
            ]
          }]
        }

  # Collection of all pages found in the league menu
  - label: 'League pages'
    label_singular: 'league page'
    name: 'league-pages'
    folder: 'src/pages/league'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'league-page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Page Sections',
          name: 'pageSections',
          widget: 'object',
          fields:
            [
              {
                label: Section,
                name: section,
                widget: list,
                fields:
                  [
                    { label: Subheading, name: subheading, widget: string },
                    { label: Image, name: image, widget: image, required: false },
                    { label: Text, name: text, widget: 'markdown' }
                  ]
              }
            ]
        }

  # Blog
  - name: 'blog'
    label: 'Blog'
    label_singular: 'blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
